### ISSUE TITLE
Build Documentation

### ISSUE THREAD

**Issue by nhanson2** [cubert-hyperspectral/cuvis.pyil#8]
The documentation to build this file and where to place the compiled file is lacking, and not intuitive to someone without experience in C++. I suggest adding expanded instructions on how to use the build script or what cmake commands should be used.

**Comment by birkholz-cubert** [comment]
We are aware of this issue an work on providing pre-compiled binaries for linux also in Q2.

In the mean-time, https://github.com/cubert-hyperspectral/cuvis.python/issues/11 provides some further insights into what needs to be done at what step. 

The build script is used by the automatic build process to provide pre-compiled versions for windows and is not designed to work on linux without modifications.

**Comment by robertCubert** [comment]
Automated script can be found [here](https://github.com/cubert-hyperspectral/cuvis.pyil/issues/10#issuecomment-2245745129)
There will be a more elegant way to do this in the future (precompiled pyil and install via pip). 
I will leave this issue open until then.
